# Task-level variables
- name: variables from play level
  hosts: localhost
  vars:
    name: "Sri"
    wish: "Good Morning"
    course: "Devops"
  tasks:
  - name: Check variables
    vars: 
      wish: "Good evening" # overrides the wish variable, because it considers in task level defined variable. 
      ansible.builtin.debug:
        msg: "Hi {{name}}, {{wish}}, learn {{course}} clearly"