# Read variable values from external file
- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: read variables from file
    ansible.builtin.debug:
      msg: "Hi {{name}}, {{wish}}, learn {{course}} clearly"