- name: datatypes printing
  hosts: web
  vars: 
    Name: sivakumar # key value
    Skills:  # Skills is a list type
    - ansible
    - python
    - java
    - sql
    Experience:  # Experience is a map type,  it contains key-value pairs 
      Ansible: 3
      Python: 2
      Java: 1
      sql: 5
    Trainer: yes # boolean type 
  tasks: 
  - name: print trainername
    ansible.builtin.debug:
      msg: "Hello, my name is {{ Name }}"
  - name: print Skills
    ansible.builtin.debug:
      msg: "My skills are {{ Skills | join(', ') }}"
  - name: print Experience
    ansible.builtin.debug:
      msg: "My experience in Ansible is {{ Experience | join(', ') }} years"
  - name: print who is trainer
    ansible.builtin.debug:
      msg: "is he a trainer {{ Trainer | upper }}"