- name: conditions
  hosts: web
  tasks: 
  - name: check roboshop user exists 
    ansible.builtin.command: id roboshop
    register: user #user is a variable name
    ignore_errors: true #ansible do not exit even it got error

  - name: print value stored in variable
    ansible.builtin.debug:
      msg: "User output is {{user}}"

  - name: print exit status of return code
    ansible.builtin.debug:
      msg: "Status is {{user.rc}}"

  - name: create user
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0 #condition 