- name: ping playbook
  hosts: localhost
  tasks: 
  - name: ping playbook
    ansible.builtin.ping:
  
  - name: print devops msg
    ansible.builtin.debug:
      msg: "hello devops"
    tags:
    - devops

  - name: print aws message
    ansible.builtin.debug:
      msg: "hello aws"
    tags:
    - aws

# to execute this tags playbook
# ansible-playbook -t <tag> <playbook.yaml>