- name: prompting variables
  hosts: web
  vars_prompt:
  - name: USERNAME
    prompt: "Enter your username"
    private: false
  - name: PASSWORD
    prompt: "Enter your password"
    private: true
  tasks:
  - name: display 
    ansible.builtin.debug:
      msg: "username is {{ USERNAME }} and password is {{ PASSWORD }}"