- name: practice
  hosts: localhost
  tasks:
  - name: practicing loops
    ansible.builtin.debug:
      name: "{{'item', 'state' }}"
    loop:
    - {name: 'git', state: 'present'}
    - {name: 'postfix', state: 'present'}
    - {name: 'mysql', state: 'present'}