- name: checking roboshop user
  hosts: web
  become: yes
  tasks:
  - name: check user roboshop exists
    ansible.builtin.command: id roboshop
    register: user
    ignore_errors: true

  - name: print value in variable
    ansible.builtin.debug:
      msg: "output is {{user}}"
  