- name: install packages
  hosts: web
  become: yes
  tasks: 
  - name: installation of packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - postfix
    - mysql
